services:
  db:
    container_name: db-dev
    image: postgres:16
    env_file:
      - local/development.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # environment:
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_DB=${DB_NAME} # This is actually the NAME of the database
  django:
    build: .
    container_name: django-dev
    command: python django/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - local/development.env
    depends_on:
      - db



volumes:
  postgres_data_dev:
    name: postgres_data_dev_volume