services:
  django:
    build: .
    container_name: django-prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - local/production.env
    environment:
      PYTHONPATH: /usr/src/app/django
    depends_on:
      - db
  db:
    container_name: db-prod
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - local/production.env

volumes:
  postgres_data_prod:
    name: postgres_data_prod_volume