services:
  web:
    build: .
    container_name: django-dev
    command: python django/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./local/development.env

  db:
    container_name: db-dev
    image: postgres:16
    env_file:
      - local/development.env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data_dev:
    name: postgres_data_dev_volume